name: Feature Request
description: Request a new feature
title: "[Feature]: "
labels: ["feature", "triage", "mvp"]
assignees:
  - elleshadow
projects:
  - "News Reader"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a new feature!
  - type: textarea
    id: new-feature
    attributes:
      label: User Story
      description: Please describe the new feature.
      value: "As a user, When I visit , I want to , so that I can "
    validations:
      required: true
  